package com.boil.dao;

import com.boil.entity.model.Robot;
import com.boil.entity.model.RobotExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RobotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    long countByExample(RobotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int deleteByExample(RobotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int insert(Robot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int insertSelective(Robot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    List<Robot> selectByExample(RobotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    Robot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Robot record, @Param("example") RobotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int updateByExample(@Param("record") Robot record, @Param("example") RobotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int updateByPrimaryKeySelective(Robot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int updateByPrimaryKey(Robot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int batchInsert(@Param("list") List<Robot> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    int batchInsertSelective(@Param("list") List<Robot> list, @Param("selective") Robot.Column ... selective);
}