package com.boil.dao;

import com.boil.model.Useraccount;
import com.boil.model.UseraccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UseraccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    long countByExample(UseraccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int deleteByExample(UseraccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int insert(Useraccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int insertSelective(Useraccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    List<Useraccount> selectByExample(UseraccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    Useraccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") Useraccount record, @Param("example") UseraccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int updateByExample(@Param("record") Useraccount record, @Param("example") UseraccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int updateByPrimaryKeySelective(Useraccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int updateByPrimaryKey(Useraccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int batchInsert(@Param("list") List<Useraccount> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    int batchInsertSelective(@Param("list") List<Useraccount> list, @Param("selective") Useraccount.Column ... selective);
}