package com.boil.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Robot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.id
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.created_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.created_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.updated_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.updated_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.wxid
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.headimgurl
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.wx_num
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    private String wxNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.id
     *
     * @return the value of robot.id
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.id
     *
     * @param id the value for robot.id
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.created_by
     *
     * @return the value of robot.created_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.created_by
     *
     * @param createdBy the value for robot.created_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.created_time
     *
     * @return the value of robot.created_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.created_time
     *
     * @param createdTime the value for robot.created_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.updated_by
     *
     * @return the value of robot.updated_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.updated_by
     *
     * @param updatedBy the value for robot.updated_by
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.updated_time
     *
     * @return the value of robot.updated_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.updated_time
     *
     * @param updatedTime the value for robot.updated_time
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.wxid
     *
     * @return the value of robot.wxid
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.wxid
     *
     * @param wxid the value for robot.wxid
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.headimgurl
     *
     * @return the value of robot.headimgurl
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.headimgurl
     *
     * @param headimgurl the value for robot.headimgurl
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.wx_num
     *
     * @return the value of robot.wx_num
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public String getWxNum() {
        return wxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.wx_num
     *
     * @param wxNum the value for robot.wx_num
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public void setWxNum(String wxNum) {
        this.wxNum = wxNum == null ? null : wxNum.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table robot
     *
     * @mbg.generated Wed Nov 18 16:32:24 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false),
        updatedBy("updated_by", "updatedBy", "VARCHAR", false),
        updatedTime("updated_time", "updatedTime", "TIMESTAMP", false),
        wxid("wxid", "wxid", "VARCHAR", false),
        headimgurl("headimgurl", "headimgurl", "VARCHAR", false),
        wxNum("wx_num", "wxNum", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table robot
         *
         * @mbg.generated Wed Nov 18 16:32:24 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}