package com.boil.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Timedtask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.id
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.created_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.created_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.updated_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.updated_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.name
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.cycletype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer cycletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.datetype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer datetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.someday
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer someday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.startingtime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer startingtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.groupnum
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private String groupnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.lasttime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private String lasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.success
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timedtask.failed
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    private Integer failed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.id
     *
     * @return the value of timedtask.id
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.id
     *
     * @param id the value for timedtask.id
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.created_by
     *
     * @return the value of timedtask.created_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.created_by
     *
     * @param createdBy the value for timedtask.created_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.created_time
     *
     * @return the value of timedtask.created_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.created_time
     *
     * @param createdTime the value for timedtask.created_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.updated_by
     *
     * @return the value of timedtask.updated_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.updated_by
     *
     * @param updatedBy the value for timedtask.updated_by
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.updated_time
     *
     * @return the value of timedtask.updated_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.updated_time
     *
     * @param updatedTime the value for timedtask.updated_time
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.name
     *
     * @return the value of timedtask.name
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.name
     *
     * @param name the value for timedtask.name
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.cycletype
     *
     * @return the value of timedtask.cycletype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getCycletype() {
        return cycletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.cycletype
     *
     * @param cycletype the value for timedtask.cycletype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setCycletype(Integer cycletype) {
        this.cycletype = cycletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.datetype
     *
     * @return the value of timedtask.datetype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getDatetype() {
        return datetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.datetype
     *
     * @param datetype the value for timedtask.datetype
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setDatetype(Integer datetype) {
        this.datetype = datetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.someday
     *
     * @return the value of timedtask.someday
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getSomeday() {
        return someday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.someday
     *
     * @param someday the value for timedtask.someday
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setSomeday(Integer someday) {
        this.someday = someday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.startingtime
     *
     * @return the value of timedtask.startingtime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getStartingtime() {
        return startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.startingtime
     *
     * @param startingtime the value for timedtask.startingtime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setStartingtime(Integer startingtime) {
        this.startingtime = startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.groupnum
     *
     * @return the value of timedtask.groupnum
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public String getGroupnum() {
        return groupnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.groupnum
     *
     * @param groupnum the value for timedtask.groupnum
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setGroupnum(String groupnum) {
        this.groupnum = groupnum == null ? null : groupnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.lasttime
     *
     * @return the value of timedtask.lasttime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public String getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.lasttime
     *
     * @param lasttime the value for timedtask.lasttime
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setLasttime(String lasttime) {
        this.lasttime = lasttime == null ? null : lasttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.success
     *
     * @return the value of timedtask.success
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.success
     *
     * @param success the value for timedtask.success
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timedtask.failed
     *
     * @return the value of timedtask.failed
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public Integer getFailed() {
        return failed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timedtask.failed
     *
     * @param failed the value for timedtask.failed
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public void setFailed(Integer failed) {
        this.failed = failed;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table timedtask
     *
     * @mbg.generated Wed Nov 18 17:54:42 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false),
        updatedBy("updated_by", "updatedBy", "VARCHAR", false),
        updatedTime("updated_time", "updatedTime", "TIMESTAMP", false),
        name("name", "name", "VARCHAR", false),
        cycletype("cycletype", "cycletype", "INTEGER", false),
        datetype("datetype", "datetype", "INTEGER", false),
        someday("someday", "someday", "INTEGER", false),
        startingtime("startingtime", "startingtime", "INTEGER", false),
        groupnum("groupnum", "groupnum", "VARCHAR", false),
        lasttime("lasttime", "lasttime", "VARCHAR", false),
        success("success", "success", "INTEGER", false),
        failed("failed", "failed", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table timedtask
         *
         * @mbg.generated Wed Nov 18 17:54:42 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}