package com.boil.entity.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.created_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.created_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.updated_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.updated_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectname
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private String projectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectcode
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private String projectcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.administrator
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    private String administrator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.created_by
     *
     * @return the value of project.created_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.created_by
     *
     * @param createdBy the value for project.created_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.created_time
     *
     * @return the value of project.created_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.created_time
     *
     * @param createdTime the value for project.created_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.updated_by
     *
     * @return the value of project.updated_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.updated_by
     *
     * @param updatedBy the value for project.updated_by
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.updated_time
     *
     * @return the value of project.updated_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.updated_time
     *
     * @param updatedTime the value for project.updated_time
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectname
     *
     * @return the value of project.projectname
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectname
     *
     * @param projectname the value for project.projectname
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectcode
     *
     * @return the value of project.projectcode
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public String getProjectcode() {
        return projectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectcode
     *
     * @param projectcode the value for project.projectcode
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode == null ? null : projectcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.administrator
     *
     * @return the value of project.administrator
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public String getAdministrator() {
        return administrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.administrator
     *
     * @param administrator the value for project.administrator
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public void setAdministrator(String administrator) {
        this.administrator = administrator == null ? null : administrator.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table project
     *
     * @mbg.generated Fri Nov 20 17:00:23 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false),
        updatedBy("updated_by", "updatedBy", "VARCHAR", false),
        updatedTime("updated_time", "updatedTime", "TIMESTAMP", false),
        projectname("projectname", "projectname", "VARCHAR", false),
        projectcode("projectcode", "projectcode", "VARCHAR", false),
        administrator("administrator", "administrator", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table project
         *
         * @mbg.generated Fri Nov 20 17:00:23 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}