package com.boil.entity.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Useraccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.id
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.created_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.created_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.updated_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.updated_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.wxid
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.name
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.headimgurl
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.id
     *
     * @return the value of useraccount.id
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.id
     *
     * @param id the value for useraccount.id
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.created_by
     *
     * @return the value of useraccount.created_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.created_by
     *
     * @param createdBy the value for useraccount.created_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.created_time
     *
     * @return the value of useraccount.created_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.created_time
     *
     * @param createdTime the value for useraccount.created_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.updated_by
     *
     * @return the value of useraccount.updated_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.updated_by
     *
     * @param updatedBy the value for useraccount.updated_by
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.updated_time
     *
     * @return the value of useraccount.updated_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.updated_time
     *
     * @param updatedTime the value for useraccount.updated_time
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.wxid
     *
     * @return the value of useraccount.wxid
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.wxid
     *
     * @param wxid the value for useraccount.wxid
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.name
     *
     * @return the value of useraccount.name
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.name
     *
     * @param name the value for useraccount.name
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.headimgurl
     *
     * @return the value of useraccount.headimgurl
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.headimgurl
     *
     * @param headimgurl the value for useraccount.headimgurl
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table useraccount
     *
     * @mbg.generated Thu Nov 19 10:54:56 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false),
        updatedBy("updated_by", "updatedBy", "VARCHAR", false),
        updatedTime("updated_time", "updatedTime", "TIMESTAMP", false),
        wxid("wxid", "wxid", "VARCHAR", false),
        name("name", "name", "VARCHAR", false),
        headimgurl("headimgurl", "headimgurl", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table useraccount
         *
         * @mbg.generated Thu Nov 19 10:54:56 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}