server:
  port: 8099
Wechat:
  messageUrl: 'http://192.168.6.113:8073/send'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boil?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root8102
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.boil.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true