server:
  port: 8099
Wechat:
  messageUrl: 'http://192.168.6.113:8073/send'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boil?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root8102
  redis:
    database: 0
    timeout: 3000
    password: youyou
    cluster:
      nodes: 47.106.8.60:6391,47.106.8.60:6392,47.106.8.60:6393,47.106.8.60:6394,47.106.8.60:6395,47.106.8.60:6396
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.boil.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true